### PR TITLE
Ruby enumerable methods project ready for review!

### PR DESCRIPTION
**Pull request by Meltrust**
### In this project I:

- Created a enumerable.rb file which contains the requested methods.
- Followed the git flow rules with a branch called "feature_methods" to merge into "develop".
- Set up the Rubocop linter.

Thanks for the review!!! :+1: )

### CODE REVIEW

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi @Meltrust  👋

Nice job on this.👌

However, let's fix these issues:

- [x] `my_each_with_index` returns the wrong output when an Array, Range, or Hash is passed along with a block.

- [x] `my_all` also returns the wrong output in cases where it is expected to return `false` it returns `true`.

- [x] `my_any` returns the wrong result when an Array of items is passed along with a simple pattern other than a class or regex.

- [x] `my_none` returns the wrong output also when a pattern is passed. 

 - [x] `my_map` returns a wrong output when both a block and a proc are passed.

- [x] `my_inject` should raise a `LocalJump Error` when no block or argument is given but yours raised nothing. In addition, it also returns the wrong output when finally a block and argument is given, also when a binary operation is passed as a second argument.

Kindly fix these issues and request another review👍
**Feel free to contact me on slack(michgolden) if you need further clarification. I would gladly reply**

HAPPY CODING👨‍💻

**Comment by mikenath223** [comment]
Finally, kindly add a `stickler.yml` file to your repo and fix the linting errors found.

**Review by rOluochKe — APPROVED** [review]
Hello Team!
### Well done and for making changes from the preview reviews :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next project. 
- Happy coding!

**Comment by Meltrust** [comment]
Thanks a lot!

**Pull request merged**
